# Site wide configuration

title:            Anita.lt
locale:           lt_LT
url:              http://dainiuxt.github.io/anita


# Jekyll configuration

permalink:   /:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Anita.lt
  avatar: bio-photo.png
  bio: 
  disqus-shortname: 
  twitter: 
  facebook: Anita.Lietuva
  google:
    plus: 
    analytics: UA-27967891-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: 
  instagram: 


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
